routers:
  - ip: "10.1.10.11"
    username: "cisco"
    password: "cisco"
    enable_password: "cisco"
    ospf:
      process_id: "1"
      router_id: "1.1.1.1"
      networks:
        - "10.0.0.0 0.0.0.255 area 0"
        - "192.168.1.0 0.0.0.255 area 0"

  - ip: "10.1.10.12"
    username: "cisco"
    password: "cisco"
    enable_password: "cisco"
    bgp:
      process_id: "65002"
      router_id: "2.2.2.2"
      log_neighbor_changes: true
      neighbors:
        - remote_ip: "172.16.10.29"
          remote_as: "65001"
          update_source: "Loopback0"

  - ip: "10.1.10.13"
    username: "cisco"
    password: "cisco"
    enable_password: "cisco"
    ospf:
      process_id: "3"
      router_id: "3.3.3.3"
      networks:
        - "10.2.0.0 0.0.0.255 area 0"
        - "192.168.3.0 0.0.0.255 area 0"
